Strings
javascript-tutorial/pl.javascript.info pull request #133
Opened 2022-06-21 14:07 UTC by RafalMichniuk

translated article about Strings

2022-06-21 14:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/pl.javascript.info?pullRequest=133) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/pl.javascript.info?pullRequest=133) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/pl.javascript.info?pullRequest=133) it.</sub>

2022-10-15 10:39 UTC, deivuss331 requested changes

2022-10-15 10:39 UTC, deivuss331 commented on 1-js/05-data-types/03-string/1-ucfirst/_js.view/test.js
> +  it("Nie wysypuje się na na pustym łańcuchu", function() {
2x "na"

2022-10-15 10:41 UTC, RafalMichniuk commented
/done

2022-10-15 10:44 UTC, deivuss331 approved these changes

2022-10-15 10:46 UTC, deivuss331 commented
@RafalMichniuk całkiem sprawnie wrzuciłeś poprawkę 😄 IMO jest ok, jak chcesz to zrób merge chyba że jeszcze ktoś doda review (ale chyba mało kto jest tu aktywny)

2022-10-15 10:49 UTC, RafalMichniuk commented
@deivuss331 dzięki! 😎 OK, poczekam tydzień (to chyba nie dużo czasu w kontekście jak tu wszystko zasuwa 😅) i jak nie pojawi się żadne review, to zrobię merge 🙂

2022-10-22 09:03 UTC, merged