Generators
javascript-tutorial/pl.javascript.info pull request #15
Opened 2019-07-26 22:56 UTC by JanKesek

I translated Generators article from English into Polish by replace english version with polish in article.md. Am i doing it right?

2019-07-26 22:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/pl.javascript.info?pullRequest=15) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/pl.javascript.info?pullRequest=15) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/pl.javascript.info?pullRequest=15) it.</sub>

2019-08-23 20:20 UTC, Verthon requested changes

2019-08-23 20:20 UTC, Verthon commented on 1-js/12-generators-iterators/1-generators/article.md
> +Zauważ prosze, kod zewnętrzny nie musi od razu wywołać `next(4)`. Może poświęcić troche czasu na wyliczenie wartości. To też jest prawidłowy kod:
Wkradła się literówka `prosze` => "proszę"
Co sądzisz o: "Wliczanie wartości może zająć trochę czasu" zamiast "Może poświęcić troche czasu na wyliczenie wartości" ?

2019-08-23 20:20 UTC, Verthon commented on 1-js/12-generators-iterators/1-generators/article.md
> +As we observed in the examples above, the outer code may pass a value into the generator, as the result of yield.
Pozostawiłeś angielską wersję w linii 407 "As we observed in the examples above, the outer code may pass a value into the generator, as the result of yield."

2019-08-28 21:27 UTC, JanKesek commented
/done

2022-10-15 10:33 UTC, deivuss331 approved these changes

2022-10-24 18:19 UTC, RafalMichniuk approved these changes

2022-10-24 18:20 UTC, merged