Error handling, "try..catch"
javascript-tutorial/pl.javascript.info pull request #90
Opened 2021-01-24 23:36 UTC by VibingCreator

2021-01-24 23:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/pl.javascript.info?pullRequest=90) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/pl.javascript.info?pullRequest=90) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/pl.javascript.info?pullRequest=90) it.</sub>

2021-11-07 13:53 UTC, akowalska622 requested changes
Minor, mostly subjective, comments. In general looks really good

2021-11-07 13:53 UTC, akowalska622 commented on 1-js/10-error-handling/1-try-catch/1-finally-or-code-after/solution.md
> +Jeśli umieścimy pierwszy fragment w środku funkcji, szybko zauważymy różnicę.
W tłumaczeniu jest trochę zmienione znaczenie, "szybko", to nie to samo co "becomes obvious"

2021-11-07 13:53 UTC, akowalska622 commented on 1-js/10-error-handling/1-try-catch/1-finally-or-code-after/solution.md
> +Występuje ona w momencie wyjścia z instrukcji `try...catch`.
Tutaj również zmienione jest znaczenie. Nie mówię, że powinno być 100% słowo w słowo, ale znaczeniowo trochę odbiega od oryginału

2021-11-07 13:53 UTC, akowalska622 commented on 1-js/10-error-handling/1-try-catch/1-finally-or-code-after/solution.md
> +    if("nie interesują mnie błędy") {
?

2021-11-07 13:53 UTC, akowalska622 commented on 1-js/10-error-handling/1-try-catch/1-finally-or-code-after/task.md
> +1. Pierwszy fragment zawiera blok `finally`, naturalnie wykona się jako ostatni ze wszystkich bloków instrukcji:
Odbiega od oryginału

2021-11-07 13:53 UTC, akowalska622 commented on 1-js/10-error-handling/1-try-catch/article.md
> +Przy użyciu instrukcji `try...catch`, możemy obsłużyć błędy w bardziej sensowny sposób.
Fajnie by było uwzględnić jeszcze jakoś ten fragment "instead of dying", to ważne, że przy try...catch nie powodujemy zatrzymania skryptu

2021-11-07 13:53 UTC, akowalska622 commented on 1-js/10-error-handling/1-try-catch/article.md
> +2. Bezbłędne wykonanie pierwszego bloku oznacza, że drugi blok `catch(err) {...}` zostaje pominięty, a program rusza dalej.
To zdanie brzmi dość skomplikowanie, nie lepiej "jeśli błąd nie wystąpi"?
Strona bierna utrudnia rozumienie, w tutorialach starajmy się jej unikać

2021-11-07 13:53 UTC, akowalska622 commented on 1-js/10-error-handling/1-try-catch/article.md
> +      alert('instrukcja została wykonana');  // *!*(1) <--*/!*
Nie została wykonana, została rozpoczęta. Gdyby została wykonana, to nie przeszlibyśmy do catch

2021-11-07 13:53 UTC, akowalska622 commented on 1-js/10-error-handling/1-try-catch/article.md
> +      alert('instrukcja nie została wykonana');  // (2)
"Never reached" jest bardzo ważnym fragmentem

2021-11-07 13:53 UTC, akowalska622 commented on 1-js/10-error-handling/1-try-catch/article.md
> +````warn header="`try...catch` umożliwia obsługę błędów napotkanych tylko w trakcie wykonywania się programu (ang. Runtime Errors)"
Proszę umieść to na tej samej linii kodu co angielska wersja, zgodnie z instrukcją w repozytorium

2021-11-07 13:53 UTC, akowalska622 commented on 1-js/10-error-handling/1-try-catch/article.md
> +Silnik JavaScript najpierw odczytuje kod, a dopiero potem go wykonuje. Błędy podczas fazy analizy kodu nie mogą zostać obsłużone w pierwszym bloku instrukcji, ponieważ niepoprawnie komunikujemy się z
Jak powyżej, pilnuj linijek

2021-11-07 13:53 UTC, akowalska622 commented on 1-js/10-error-handling/1-try-catch/article.md
> -: Current call stack: a string with information about the sequence of nested calls that led to the error. Used for debugging purposes.
Warto dodać w nawiasie (ang. call stack)

2021-11-07 13:53 UTC, akowalska622 commented on 1-js/10-error-handling/1-try-catch/article.md
> +## Zastosowanie "try...catch" w życiu codziennym
Po co dopisek "w życiu codziennym"?

2021-11-07 13:53 UTC, akowalska622 commented on 1-js/10-error-handling/1-try-catch/article.md
> +Na tym etapie powinniśmy już wiedzieć o metodzie [JSON.parse(str)](mdn:js/JSON/parse), która umożliwia nam przetworzenie obiektu JSON.
Lepiej trzymać się tu oryginalnej wersji "Jak już wiemy". 
"Powinniśmy"  może stawiać czytelnika w pozycji, nomen omen, powinności, co nie jest tu dobrym konstruktem

2022-10-28 23:34 UTC, bartek7 commented
Hej, zacząłem tłumaczyć ten rozdział. Czy dany pull request jest jeszcze w miarę aktualny i powinienem przestać tłumaczyć czy jak? Na liście tłumaczeń nie było tego tematu zajętego.

2022-10-29 11:41 UTC, RafalMichniuk commented
Hej, wydaje mi się, że jeśli nie było nikogo przypisanego, to możesz śmiało jechać z tematem 🙂
Jeśli chcesz sobie zaoszczędzić pracy, to możesz zaciągnąć aktualny progres tego tłumaczenia i zastosować się do komentarzy.
Widzę, że przypisałeś się również do innego tematu. Ilość tłumaczeń się oczywiście ceni, ale postaraj się nie przypisywać siebie do kolejnego tłumaczenia, jeśli nie skończyłeś tłumaczyć pierwszego wybranego tematu.

2022-10-29 11:52 UTC, bartek7 commented
@RafalMichniuk 
Nie, nie. Nie chcę po kimś poprawiać. Za dużo tego robię w codziennej pracy. Zacznę od zera, tymbardziej, że uważam, że te tłumaczenia nie powinny być 1:1 do składane zdania są wtedy komiczne.

Co do ilości tłumaczonych tematów w jednym momencie - teoretycznie masz rację, ale tematy, które wziąłem są ze sobą ściśle powiązane. Więc wolałem się za nie zabrać w 100%. Z drugiej strony widzę, że tłumaczenia idą jak krew z nosa, więc akurat w tym przypadku cieszmy się, że ktokolwiek chce to tłumaczyć.

2022-10-29 12:08 UTC, RafalMichniuk commented
Przyznaję, że w tym wypadku oczywiście masz rację, jednak na przyszłość postaraj się trzymać wytycznych zawartych w opisie dla tłumaczących: [For New Translators](https://github.com/javascript-tutorial/pl.javascript.info/issues/1#For%20New%20Translators)

2022-10-29 12:33 UTC, bartek7 commented
Luzik arbuzik :)

2023-03-28 20:42 UTC, closed without merging